### ISSUE TITLE
Error requesting the access token with `user-soa-unlink` scope

### ISSUE THREAD

**Issue by carlosbaraza** [spotify/soa-reference-integration#1]
Hello @rubenLindstrom (sorry for mentioning directly), 

We are encountering an error requesting the access token with `user-soa-unlink` scope. I wonder if there is an issue with the authentication API that is not supporting the SOA scopes.

Error calling the function `requestClientAccessToken` to request access tokens:

```tsx
{
  "error": "invalid_scope",
  "error_description": "Invalid scope"
}
```

Other scopes work well. For example the `soa-manage-entitlements` scope works

[https://developer.spotify.com/documentation/open-access/reference/#/operations/unlink-user](https://developer.spotify.com/documentation/open-access/reference/#/operations/unlink-user)

**Comment by cjallen88** [comment]
Hey, we are also encountering this! Frustratingly, the running app https://lunar-industries.spotify.com/ has no problem unlinking users... @carlosbaraza did you figure out what the problem was at all?

Example sanitised curl command:
```
curl --request POST \
  --url https://accounts.spotify.com/api/token \
  --header 'Authorization: Basic <encoded client/secret>' \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --data 'grant_type=client_credentials&scope=user-soa-unlink'
```

**Comment by carlosbaraza** [comment]
@cjallen88 We didn't solve it in the end. But apparently they need to give permissions manually for this scope.

**Comment by cjallen88** [comment]
Thanks for the reply!

**Comment by rubenGripberg** [comment]
Hi, sorry for the slow response, the notification did not reach me! 

You're entirely correct that a separate scope is needed for the /unlink endpoint, which did not use to be included by default for new SOA partners. This has since been addressed, and it is automatically added to the Spotify Developer account.

If you integrated before this change and would like to make use of the /unlink endpoint, please contact partnership support and we will fix that for you.

Very much appreciate the feedback, closing this issue for now, and don't hesitate to reach out should you have any other questions or concerns!
